<a href="https://colab.research.google.com/github/rahulsait/ExcelR-codes/blob/main/HYPOTHESIS_TESTING_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Q] A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units.**
## **A randmoly selected sample of cutlets was collected from both units and measured. Analyze the data and draw inferences at 5% significance level.**
## **Please state the assumptions and tests that you carried out to check validity of the assumptions.**

## **ANS]**
### *Since we have two units of samples to compare - we perform a **two-sample** test.*


### *Assuming the Hypothesis :*
### *Let m1 be the average diameter of the cutlets in 1st Sample.*
### *Let m2 be the average diameter of the cutlets in 2nd Sample.*

**H0 : m1 = m2 (No significant difference in the diameter of cutlets in both units)**

**Ha : m1 =! m2 (Presence of a significance difference in the diameter of cutlets in both units)**

In [32]:
import numpy as np
import pandas as pd
import scipy
from scipy import stats

In [29]:
alpha = 0.05

In [30]:
significance_value = alpha


In [31]:
significance_value

0.05

In [33]:
data = pd.read_csv("/content/Cutlets.csv")

In [17]:
data

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

*dividing the data into two units :*

In [34]:
unit_A = data["Unit A"]

In [35]:
unit_A

0     6.8090
1     6.4376
2     6.9157
3     7.3012
4     7.4488
5     7.3871
6     6.8755
7     7.0621
8     6.6840
9     6.8236
10    7.3930
11    7.5169
12    6.9246
13    6.9256
14    6.5797
15    6.8394
16    6.5970
17    7.2705
18    7.2828
19    7.3495
20    6.9438
21    7.1560
22    6.5341
23    7.2854
24    6.9952
25    6.8568
26    7.2163
27    6.6801
28    6.9431
29    7.0852
30    6.7794
31    7.2783
32    7.1561
33    7.3943
34    6.9405
Name: Unit A, dtype: float64

In [36]:
unit_B = data["Unit B"]

In [37]:
unit_B

0     6.7703
1     7.5093
2     6.7300
3     6.7878
4     7.1522
5     6.8110
6     7.2212
7     6.6606
8     7.2402
9     7.0503
10    6.8810
11    7.4059
12    6.7652
13    6.0380
14    7.1581
15    7.0240
16    6.6672
17    7.4314
18    7.3070
19    6.7478
20    6.8889
21    7.4220
22    6.5217
23    7.1688
24    6.7594
25    6.9399
26    7.0133
27    6.9182
28    6.3346
29    7.5459
30    7.0992
31    7.1180
32    6.6965
33    6.5780
34    7.3875
Name: Unit B, dtype: float64

In [38]:
stats.ttest_ind(unit_A,unit_B)

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

In [39]:
p_value = stats.ttest_ind(unit_A,unit_B)[1]

In [40]:
p_value

0.4722394724599501

In [41]:
if p_value > significance_value :
  print("Accept H0 : No Significant difference in the diameter")
else :
  print("Reject H0 : Presence of significant different in the diameter")

Accept H0 : No Significant difference in the diameter


## **Q] A Hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.**

## **Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.**

## **ANS]**

## Since we have to compare among 4 laboratories - we use **Anova Test**

## *Assuming the Hypothesis :*

**H0 : No such Significant difference in the average TAT among all the laboratories.**

**Ha : Presence of Significant difference in the average TAT among all the laboratories.**

In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
from scipy import stats
%matplotlib inline

In [43]:
# reading the dataset :
data = pd.read_csv("/content/LabTAT.csv")

In [44]:
data.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [47]:
data["Laboratory 2"]

0      165.53
1      185.91
2      194.92
3      183.00
4      169.57
        ...  
115    170.66
116    183.98
117    174.54
118    197.18
119    215.17
Name: Laboratory 2, Length: 120, dtype: float64

In [48]:
# Using the iloc function would be handy than using data["Column name"]
data.iloc[:,1]

0      165.53
1      185.91
2      194.92
3      183.00
4      169.57
        ...  
115    170.66
116    183.98
117    174.54
118    197.18
119    215.17
Name: Laboratory 2, Length: 120, dtype: float64

In [49]:
# Passing all the 4 columns to ANOVA : to get the p-value
stats.f_oneway(data.iloc[:,0], data.iloc[:,1], data.iloc[:,2], data.iloc[:,3])

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [50]:
p_value = stats.f_oneway(data.iloc[:,0], data.iloc[:,1], data.iloc[:,2], data.iloc[:,3])[1]

In [51]:
p_value

2.1156708949992414e-57

In [52]:
significance_value = 0.05

In [54]:
# checking the hypothesis :
if p_value > significance_value :
  print("Accept H0 : No such Significant difference in the average TAT among the 4 laboratories.")
else :
  print("Reject H0 : Contains a Significant different in the average TAT among the 4 laboratories.")

Reject H0 : Contains a Significant different in the average TAT among the 4 laboratories.


## **Q] Sales of products in four different regions is tabulated for males and females.**
## **Find if male-female buyer proportions are similar across regions.**

## **ANS]**
Since we have to compare features of two categorical variables, we use **Chi Square test**

### **Listing Hypothesis :**
**H0 :** *All Proportions are Equal*

**Ha :** *Not all Proportions are Equal*

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
from scipy import stats
%matplotlib inline

In [2]:
# loading the dataset :
data = pd.read_csv("/content/BuyerRatio.csv")

In [4]:
data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [18]:
ds = data.iloc[:,1:5]

In [21]:
ds

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [19]:
ds.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [20]:
print("Observed Values : \n", ds.values)

Observed Values : 
 [[  50  142  131   70]
 [ 435 1523 1356  750]]


In [22]:
val = stats.chi2_contingency(ds)

In [23]:
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [24]:
Expected_values = val[3]

In [25]:
print("Expected Values : \n", Expected_values)

Expected Values : 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [26]:
# computing degrees of freedom (dof):
no_of_rows = 2
no_of_columns = 4
dof = (no_of_rows - 1)*(no_of_columns - 1)


In [27]:
dof

3

In [28]:
alpha = 0.05

In [29]:
from scipy.stats import chi2

In [31]:
chi_square = sum([(o - e)**2./e for o,e in zip(ds.values, Expected_values)])

In [32]:
chi_square

array([1.34226039e+00, 1.73035255e-01, 1.15612650e-04, 8.05342809e-02])

In [33]:
# adding up the above 4 rows to get the chi square test statistics value :
chi_square_statistic = chi_square[0] + chi_square[1] + chi_square[2] + chi_square[3]

In [34]:
print("Chi Square Test Statistic : \n", chi_square_statistic)

Chi Square Test Statistic : 
 1.5959455386610577


In [35]:
# computing chi square critical value :
critical_value = chi2.ppf(q=1-alpha, df = dof)
print("Critical Value : \n", critical_value)

Critical Value : 
 7.814727903251179


In [36]:
print("Chi Square Test Statistic : ", chi_square_statistic)
print("Critical value : ", critical_value)
print("Significance value : ", alpha)

Chi Square Test Statistic :  1.5959455386610577
Critical value :  7.814727903251179
Significance value :  0.05


In [38]:
# Comparing chi square test statistic and critical value :
if chi_square_statistic >= critical_value :
  print("Reject H0 : Not all Proportions are equal")
else :
  print("Accept H0 : All Proportions are equal")

Accept H0 : All Proportions are equal


In [39]:
# Computing P-Value :
p_value = 1 - chi2.cdf(x = chi_square_statistic, df = dof)
print("p-value : \n", p_value)

p-value : 
 0.6603094907091882


In [40]:
# Comparing P-Value with Significance Value :
if p_value >= alpha :
  print("Accept H0 : All Proportions are equal")
else :
  print("Reject H0 : Not all Proportions are equal")

Accept H0 : All Proportions are equal


## **Q] TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain % of the customer order forms. Any error in order form renders it defective and has to be reworked before processing. The manager wants to check whether the defective % varies by center. Please analyze the data at 5% significance level and help the manager draw appropriate inferences.**

## **ANS]**
Since we got to compare among 4 Categorical Variables - We use **Chi Square Test**

### **Listing Hypothesis :**
**H0 : All Centers have the same Defective %**

**Ha : Atleast one Center has varying Defective %**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
from scipy import stats
%matplotlib inline

In [2]:
# loading the dataset :
ds = pd.read_csv("/content/Costomer+OrderForm.csv")

In [3]:
ds.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [5]:
ds.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [6]:
ds.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [7]:
ds.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [8]:
ds.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [9]:
# Creating an array with the above values :
data = np.array([[271,267,269,280],[29,33,31,20]])

In [16]:
observed_values = data

In [17]:
observed_values

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [18]:
val = stats.chi2_contingency(data)

In [19]:
val

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [20]:
expected_values = val[3]

In [21]:
from scipy.stats.contingency import expected_freq
expected_values

array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

In [22]:
# computing Degrees of freedom (dof) :
no_of_rows = 2
no_of_col = 4
dof = (no_of_rows-1)*(no_of_col-1)

In [23]:
dof

3

In [35]:
alpha = 0.05

In [25]:
from scipy.stats import chi2
chi_square = sum([(o-e)**2./e for o,e in zip(observed_values,expected_values)])

In [26]:
chi_square

array([0.02198142, 0.88169925, 0.295528  , 2.65975202])

In [27]:
chi_square_statistic = chi_square[0] + chi_square[1] + chi_square[2] + chi_square[3]

In [28]:
chi_square_statistic

3.8589606858203545

In [36]:
# computing chi square critical value :
critical_value = chi2.ppf(q=1-alpha, df=dof)

In [37]:
critical_value

7.814727903251179

In [38]:
# Comparing test statistic and critical value :
if chi_square_statistic >= critical_value :
  print("Reject H0 : Atleast one Center has varying Defective %")
else :
  print("Accept H0 :  All Centers have the same Defective %")

Accept H0 :  All Centers have the same Defective %


In [39]:
# computing P-Value :
p_value = 1 - chi2.cdf(x = chi_square_statistic, df = dof)

In [40]:
p_value

0.2771020991233144

In [41]:
# Comparing P-Value with Alpha :
if p_value > alpha :
  print("Accept H0 : All Centers have the same Defective %")
else :
  print("Reject H0 : Atleast one Center has varying Defective %")

Accept H0 : All Centers have the same Defective %


## **: From the above analysis we can conclude that all Centers around the globe have the same defective %.**