<a href="https://colab.research.google.com/github/rahulsait/ExcelR-codes/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**NUMPY** for **EDA**
###**NumPY ~ Numerical Python**

In [1]:
import numpy as np

In [2]:
x = {1,2,3,4,5,6,7,8,9,10}
print(x)
print(type(x))

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
<class 'set'>


In [6]:
y = [1,2,3,4,5]
print(y)
type(y)
print(y*2) # values of the list are repeated but not multiplied by 2

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


    numpy array will help access the values

In [7]:
arry = np.array(y)
print(arry)
type(arry)

[1 2 3 4 5]


numpy.ndarray

In [8]:
print(arry*2) # each element is mutliplied by 2 and the output gets printed as below

[ 2  4  6  8 10]


In [11]:
arry > 3 # checks which elements of arry > 3
# True ~ 1 ; False ~ 0

array([False, False, False,  True,  True])

In [17]:
arry[arry > 3] # returns or retrieves the elements satisfying this condition

array([4, 5])

In [26]:
from numpy import random # imports the random submodel(function or method) from numpy

x = random.randint(1,9) # generates a random int between a specified range
print(x) # first arg is included ie. 1 here and excludes next arg ie. 9 in this case

2


In [27]:
print(x)

2


##**Memory Savers :**
    "Memory saver" in Python refers to techniques and practices
    aimed at reducing the amount of memory a Python program consumes during execution.
    This is crucial for performance,
    especially when dealing with large datasets or running applications on systems with limited resources.

    numpy arrays share the memory instead of allocating seperate memories

In [35]:
arr = np.arange(0,21)
print(arr)
print(type(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>


In [36]:
arr1 = np.arange(21)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [38]:
arr2 = arr1[2 : 17 : 3]
print(arr2)

[ 2  5  8 11 14]
